"""add is_alive

Revision ID: edc064728d74
Revises: f4d0bc11ebab
Create Date: 2025-12-04 01:28:46.099395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'edc064728d74'
down_revision: Union[str, None] = 'f4d0bc11ebab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_alive', sa.Boolean(), nullable=True))
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'race',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'weapon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'hp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'strength',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'dexterity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('characters', 'created_at')
    op.add_column('story_messages', sa.Column('user_input', sa.String(), nullable=True))
    op.add_column('story_messages', sa.Column('ai_response', sa.String(), nullable=True))
    op.add_column('story_messages', sa.Column('image_base64', sa.String(), nullable=True))
    op.alter_column('story_messages', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('story_messages', 'content')
    op.drop_column('story_messages', 'role')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('story_messages', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('story_messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('story_messages', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('story_messages', 'image_base64')
    op.drop_column('story_messages', 'ai_response')
    op.drop_column('story_messages', 'user_input')
    op.add_column('characters', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.alter_column('characters', 'dexterity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'strength',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'hp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'weapon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characters', 'race',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('characters', 'is_alive')
    # ### end Alembic commands ###
